
name: Build

on: [push, pull_request]

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-win-x64,  test-win-x64]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with: 
        name: build-win-x64
        path: win-x64
    - name: Pack
      run: |
        zip -r win-x64.zip ./win-x64/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
         files: win-x64.zip

  test-win-x64:
    runs-on: windows-latest
    needs: build-win-x64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with: 
        name: build-win-x64
        path: ctx/coremod
    - name: Copy hlboot
      run: |
        Copy-Item -Path ./hlboots/hlboot-directx-steam.dat -Destination "./ctx/hlboot.dat" -Recurse -Force
    - name: Install MDK
      run: |
        echo "DCCM_MDK_ROOT=$env:GITHUB_WORKSPACE/ctx/coremod/core/mdk" >> $env:GITHUB_ENV
        echo "DEAD_CELLS_GAME_PATH=$env:GITHUB_WORKSPACE/ctx" >> $env:GITHUB_ENV
        ./ctx/coremod/core/mdk/install.ps1
    - name: Build ModCore
      run: |
        ./buildWin.ps1 -BuildNative 0 -BuildMDK 0
    - name: Run Tests
      run: |
        cd sources
        dotnet test


  build-win-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Download Dependencies
      run: |
        cd ./sources/native/3rd/hashlink/include

        Invoke-WebRequest -Uri https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip -OutFile ./OpenAL.zip
        Expand-Archive -LiteralPath ./OpenAL.zip -DestinationPath . -Force
        Move-Item -Path ./openal-soft-1.23.1-bin -Destination ./openal -Force
        
        Invoke-WebRequest -Uri https://www.libsdl.org/release/SDL2-devel-2.30.2-VC.zip -OutFile ./SDL.zip
        Expand-Archive -LiteralPath ./SDL.zip -DestinationPath . -Force
        Move-Item -Path ./SDL2-2.30.2 -Destination ./sdl -Force

    - name: Build
      run: ./buildWin.ps1

    - name: Upload
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-win-x64
        path: ./bin/*
